find_package(Qt6 6.4 COMPONENTS Core Qml)

qt_add_qml_module(Source
    URI core.source
    VERSION 1.0
    SOURCES
        Common/ModifierSource.cpp
        Common/ModifierSource.h
        Common/RequirementSource.cpp
        Common/RequirementSource.h

        Model/Items/ItemNameProxyModel.h
        Model/Items/ItemNameProxyModel.cpp
        Model/Items/ItemSourceModel.h
        Model/Items/ItemSourceModel.cpp
        Model/Items/ItemSourceFilterProxyModel.h
        Model/Items/ItemSourceFilterProxyModel.cpp
        Model/Items/ItemsSortProxyModel.h
        Model/Items/ItemsSortProxyModel.cpp
        Model/Items/ShopItemSource.h
        Model/Items/ShopItemSource.cpp

        Model/AvailableFilterProxyModel.cpp
        Model/AvailableFilterProxyModel.h
        Model/BougthFilterProxyModel.h
        Model/BougthFilterProxyModel.cpp
        Model/NameFilterProxyModel.cpp
        Model/NameFilterProxyModel.h
        Model/RequirementFilterProxyModel.cpp
        Model/RequirementFilterProxyModel.h
        Model/RequirementSourceModel.cpp
        Model/RequirementSourceModel.h
        Model/TrickSortProxyModel.cpp
        Model/TrickSortProxyModel.h
        Model/TrickSourceItem.cpp
        Model/TrickSourceItem.h
        Model/TrickSourceModel.cpp
        Model/TrickSourceModel.h
        Model/TrickSourceSortFilterProxyModel.cpp
        Model/TrickSourceSortFilterProxyModel.h

        Statistics/AttributeSource.cpp
        Statistics/AttributeSource.h
        Statistics/Bonus/AttributeBonusList.cpp
        Statistics/Bonus/AttributeBonusList.h
        Statistics/Bonus/AttributeBonusSingle.cpp
        Statistics/Bonus/AttributeBonusSingle.h
        Statistics/Bonus/AttributeBonusSource.h
        Statistics/Bonus/BonusBeast.cpp
        Statistics/Bonus/BonusBeast.h
        Statistics/Bonus/BonusFame.cpp
        Statistics/Bonus/BonusFame.h
        Statistics/Bonus/BonusFeatures.cpp
        Statistics/Bonus/BonusFeatures.h
        Statistics/Bonus/BonusFriend.cpp
        Statistics/Bonus/BonusFriend.h
        Statistics/Bonus/BonusHealth.cpp
        Statistics/Bonus/BonusHealth.h
        Statistics/Bonus/BonusReputation.cpp
        Statistics/Bonus/BonusReputation.h
        Statistics/Bonus/BonusSkillpack.cpp
        Statistics/Bonus/BonusSkillpack.h
        Statistics/Bonus/BonusSkillpackDL.cpp
        Statistics/Bonus/BonusSkillpackDL.h
        Statistics/Bonus/BonusSkillpoints.cpp
        Statistics/Bonus/BonusSkillpoints.h
        Statistics/Bonus/BonusSkills.cpp
        Statistics/Bonus/BonusSkills.h
        Statistics/Bonus/BonusSource.h
        Statistics/Bonus/BonusTrick.cpp
        Statistics/Bonus/BonusTrick.h
        Statistics/DiseaseSource.cpp
        Statistics/DiseaseSource.h
        Statistics/FeatureSource.cpp
        Statistics/FeatureSource.h
        Statistics/OriginSource.cpp
        Statistics/OriginSource.h
        Statistics/OtherSkillSource.cpp
        Statistics/OtherSkillSource.h
        Statistics/ProfessionSource.cpp
        Statistics/ProfessionSource.h
        Statistics/QuestionSource.cpp
        Statistics/QuestionSource.h
        Statistics/SkillSource.cpp
        Statistics/SkillSource.h
        Statistics/SkillpackSource.cpp
        Statistics/SkillpackSource.h
        Statistics/SpecializationSource.cpp
        Statistics/SpecializationSource.h
        Statistics/StatisticsSource.cpp
        Statistics/StatisticsSource.h
        Statistics/SymptomSource.cpp
        Statistics/SymptomSource.h
        Statistics/TrickSource.cpp
        Statistics/TrickSource.h

        Equipment/AmmunitionSource.h
        Equipment/AmmunitionSource.cpp
        Equipment/ArmorSource.h
        Equipment/ArmorSource.cpp
        Equipment/DrugSource.h
        Equipment/DrugSource.cpp
        Equipment/DefenceSource.h
        Equipment/DefenceSource.cpp
        Equipment/ItemSource.h
        Equipment/HandWeaponSource.h
        Equipment/HandWeaponSource.cpp
        Equipment/HandWeaponDamageSource.h
        Equipment/HandWeaponDamageSource.cpp
        Equipment/HandWeaponBonusSource.h
        Equipment/HandWeaponBonusSource.cpp
        Equipment/MotorVehicleSource.h
        Equipment/MotorVehicleSource.cpp
        Equipment/OtherSource.h
        Equipment/OtherSource.cpp
        Equipment/RangeWeaponSource.h
        Equipment/RangeWeaponSource.cpp
        Equipment/ShieldSource.h
        Equipment/ShieldSource.cpp
        Equipment/WeaponModSource.h
        Equipment/WeaponModSource.cpp
        Equipment/WeaponRequirementSource.h
        Equipment/WeaponRequirementSource.cpp
        Equipment/WeaponSpecialSource.h
        Equipment/WeaponSpecialSource.cpp

        Validators/TrickRequirementsValidator.h
        Validators/TrickRequirementsValidator.cpp

        SourceConverter.cpp
        SourceConverter.h
        SourceDocument.cpp
        SourceDocument.h
        SourceLoader.cpp
        SourceLoader.h
)

target_include_directories(Source
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/Common
        ${CMAKE_CURRENT_SOURCE_DIR}/Model
        ${CMAKE_CURRENT_SOURCE_DIR}/Model/Items
        ${CMAKE_CURRENT_SOURCE_DIR}/Equipment
        ${CMAKE_CURRENT_SOURCE_DIR}/Statistics
        ${CMAKE_CURRENT_SOURCE_DIR}/Statistics/Bonus
        ${CMAKE_CURRENT_SOURCE_DIR}../Creation/Common/
        ${CMAKE_CURRENT_SOURCE_DIR}../Creation/Statistics/
)

target_link_libraries(Source
    PRIVATE
        Data
        Utils
)
